# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
APP_KEY: 7nljmim39v018zo
APP_SECRET: fw17pm6lmxdqt2z
ACCESS_TOKEN: 1ct241926klrz949
ACCESS_TOKEN_SECRET: z7mbdlz2i38weqn
USER_ID: "424921669"

production:
  APP_KEY: 7nljmim39v018zo
  APP_SECRET: fw17pm6lmxdqt2z
  ACCESS_TOKEN: 1ct241926klrz949
  ACCESS_TOKEN_SECRET: z7mbdlz2i38weqn
  USER_ID: "424921669"
  
